### PR TITLE
Fix deprecated app.info warning, removed in Sphinx 2.x

### PR DESCRIPTION
**Pull request by doctorlard**

### CODE REVIEW

**Comment by doctorlard** [comment]
Fixes #26

**Comment by andreykashcheev** [comment]
Any ETA when this change will be merged and available? This issue blocks switching to Sphinx 2.0
Please advise!

**Comment by doctorlard** [comment]
I hope @tell-k can let us know :-)

**Comment by tell-k** [comment]
@doctorlard sorry to late my reply. 

LGTM thank you for your help

**Pull request merged**
